### ISSUE TITLE
bower.json should restrict to dojo 1.x

### ISSUE THREAD

**Issue by wkeese** [SitePen/dstore#223]
bower.json says:

```
"dojo": ">=1.8.1"
```

That will inadvertently start to load dojo 2.0 (when dojo 2.0 goes production), but really dstore only works with dojo 1.x, right?   So I think it should say:

```
"dojo" "^1.8.1"
```

(I could be wrong though, I'm not a semver expert.)

**Comment by dylans** [comment]
Dojo 2 (and later 3, 4, and 5) have been in production for nearly a year, but because we chose not to use the dojo/dojo package, I don't think this is an issue. That said, you're correct if we were planning to continue with a dojo/dojo package that was not compatible with Dojo 1.x. However, given that bower has been deprecated for about 1.5 years now, we should probably consider removing bower support as suggested on https://bower.io/blog/ .

**Comment by wkeese** [comment]
You've already made a Dojo 5???

Anyway, I got confused because https://semver.npmjs.com/ lists Dojo 2.0 alpha, but no Dojo 2.0.

We haven't gotten around to updating our code from bower, i.e. we are still loading dstore through bower, but I guess even if you desupported bower as suggested in that link, we would be OK as long as (like that link says) you didn't unregister dstore from bower.

**Comment by dylans** [comment]
Yes, a new major release of Dojo with minor breaking changes (and automatic upgrade scripts between versions) is planned for roughly every 3 months... https://dojo.io/blog/ has details about each release.

I don’t think we plan to unregister bower support, but we may remove bower.json from a future release.

**Comment by wkeese** [comment]
Feel free to close this then.  The package.json does say `"dojo": "^1.9.0"` so at least it's clear about which dojo version to use.
