### ISSUE TITLE
RequestMemory does not emit 'add' events

### ISSUE THREAD

**Issue by chrislong** [SitePen/dstore#96]
From my experiments, it looks like RequestMemory does not emit 'add' events when it gets populated. I tried 

    myRequestMemory.on('add', function() { ... })

but the callback is never called. Maybe this is how it's supposed to work, but if so, it would be nice if the documentation said so. Since a Store is an extension of the Collection API, I expected all the Stores to implement these events.

I was able to work around it by instead putting listeners on the cache, like:

    myRequestMemory.cachingStore.on('add', function() { ... })

**Comment by kriszyp** [comment]
I added verification of these events here https://github.com/SitePen/dstore/commit/e03c1b5d1c8a405478caa2fb159b23f8c957f4a7. Do you have more specific details on how and when they might be missing?

**Comment by kfranqueiro** [comment]
Could this be because `RequestMemory`'s main store uses `Request` which doesn't implement `add`, `put`, and `remove`?  (The Memory store used as the cache does, but that's not the main store.)

**Comment by kfranqueiro** [comment]
@kriszyp: If I poke a bit at the tests you added, I notice the following:

* `event.target` is undefined
* If I attempt to listen to the event on a tracked collection based off of the store instead of the store itself, they don't seem to fire at all

**Comment by kfranqueiro** [comment]
I did some more digging on this this morning with a colleague.  Here's a brief run-down of my observations:

* While most of dstore's OOTB stores switch `autoEmitEvents` to `false`, Request doesn't because it normally doesn't govern write methods (and Cache doesn't because it expects to have no opinion on the matter, expecting the store it extends to handle it)
* I expect that the reason `event.target` is undefined in my observations yesterday is because of https://github.com/SitePen/dstore/pull/107 - `add` and `put` currently return `undefined` from Cache because there is no method to inherit from Request
* I suspect that `autoEmitEvents: true` may have never been tested with a tracked collection...  more specifically, I suspect that the aspected methods it creates in `Store#constructor` will get lost on sub-collections

**Comment by kriszyp** [comment]
I tried to add tests to validate the situations you mentioned. Perhaps #107 fixed all of these?

**Comment by kfranqueiro** [comment]
Hm, yeah...  I just re-tried some things, and while they weren't working against the first commit you added, they're working now against master.  I would've thought that the autoEmitEvents stuff might pose a problem, but maybe not?

The fix for #107 will get backported to the 1.0 branch too, right?

**Comment by kriszyp** [comment]
Yes, I just backported it.
