### ISSUE TITLE
Trackable does not preserve totalLength property on fetch results

### ISSUE THREAD

**Issue by kfranqueiro** [SitePen/dstore#97]
At https://github.com/SitePen/dstore/blob/v1.0.1/Trackable.js#L98, the `fetch` function created by `makeFetch` returns a chained promise off of the original `QueryResults` object, losing any additional information such as `totalLength`.  This will cause consumers that expect proper `QueryResults` to fail.  (For example, this affects dgrid with Pagination and Tree, since it uses `fetch` for rendering children in that case.)

I've created a [`trackable-fetch-test` branch](https://github.com/kfranqueiro/dstore/commits/trackable-fetch-test) with failing unit tests.

Meanwhile, fwiw, I suspect those `when` calls in Trackable's fetch/fetchRange functions can be simplified to use `then` now that the APIs are always async.

**Comment by kriszyp** [comment]
I am hesitant to backport this to 1.0.x since it slightly modifies the behavior of fetch, such that the array return from fetch (and fetchSync) is no longer updated/maintained by Trackable (it maintains a separate internal array). This is actually more consistent, as it matches the behavior of fetchRange, and I think more closely follows the intent of fetch, in that it returns a snapshot of data. However, this change in behavior seems like it would fit better in a 1.x release.

**Comment by kfranqueiro** [comment]
This particular issue isn't terribly hard to work around, so that might be reasonable, and I'm generally all for not destabilizing existing minor lines.  I think Colin will also be happy that it is getting eventually addressed either way. :)
